# Generated by Django 2.1.1 on 2018-10-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
