# Generated by Django 2.1.1 on 2018-11-21 07:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='relationship',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
