# Generated by Django 2.1.1 on 2018-12-07 12:44

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181121_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=500)),
                ('degree', models.CharField(blank=True, max_length=300)),
                ('field_of_study', models.CharField(blank=True, max_length=300)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('from_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('to_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_follower', models.CharField(max_length=350)),
                ('follow_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('company_name', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('from_year', models.PositiveIntegerField(blank=True, null=True)),
                ('to_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='certifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_image',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_self_thumb',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_self_video',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='professional_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='college',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to=settings.AUTH_USER_MODEL),
        ),
    ]
