const mongoose = require('mongoose');

const BusinessHours = new mongoose.Schema({
  weekday: { type: String },
  availability: { type: String },
  opensfrom: { type: String },
  closedat: { type: String },
});

const eventServiceFaqs = new mongoose.Schema({
  faqnumber: { type: String },
  faqquestion: { type: String },
  faqanswer: { type: String },
});

const eventServiceSchema = new mongoose.Schema({
  adminid: { type: mongoose.Schema.Types.ObjectId, ref: 'user' },
  firstname: { type: String },
  lastname: { type: String },
  email: { type: String },
  phone: { type: String },
  servicetype: { type: String },
  companyname: { type: String },
  venue: { type: String },
  address1: { type: String },
  address2: { type: String },
  zipcode: { type: String },
  city: {type: String},
  state: { type: String },
  country: { type: String },
  websitelink: { type: String },
  venuedescription: { type: String },
  coverpage: { type: String },
  coverpageurl: { type: String },
  businesslogo: { type: String },
  businesslogourl: { type: String},
  businesshours: [BusinessHours],
  customerengagementbutton: { type: String },
  customerengagementform: {
    eventtype: { type: String },
    eventcity: { type: String },
    eventname: { type: String },
    eventemail: { type: String },
    eventphone: { type: String },
    eventdate: { type: String },
    eventtime: { type: String },
  },
  comments: { type: String },
  producttitle1: { type: String },
  productfile1: { type: String },
  productfile1url: { type: String },
  productfile1thumb: { type: String },
  productheading1: { type: String },
  productdescription1: { type: String },
  producttitle2: { type: String },
  productfile2: { type: String },
  productfile2url: { type: String },
  productfile2thumb: { type: String },
  productheading2: { type: String },
  productdescription2: { type: String },
  businesscoverageareas: { type: Array },
  rankclientbase: { type: String },
  businesssearchkeywords: { type: Array },
  discount1: {type: String},
  dicountbegin1: { type: String},
  discountend1: {type: String},
  discount2: {type: String},
  dicountbegin2: { type: String},
  discountend2: {type: String},
  eventservicefaqs: [eventServiceFaqs],
  createdAt: { type: String },
});

module.exports = mongoose.model('eventservice', eventServiceSchema);
